version: "3.8"

services:
  rust:
    container_name: functional_rust
    build: .
    tty: true
    volumes:
      - ./rust:/workspace
  scala:
    container_name: scala
    image: sbtscala/scala-sbt:eclipse-temurin-17.0.4_1.7.1_3.2.0
    tty: true
    volumes: 
      - ./scala:/workspace